Modularizing
onna/pypm pull request #2
Opened 2018-02-23 19:55 UTC by hnykda

Hey. 

I created from this a proper module, removed unused imports and used argparse. Totally fine if you don't want to merge it, just so you know.

@elifiner should probably know about this as well.

2018-02-23 22:34 UTC, elifiner commented
Hey @hnykda, thanks for pinging me on this, I had no idea anybody was using that old module let alone forking and extending it. It's awesome! Looks like maybe @masipcat is the closest thing to an official maintainer of pypm at this point.

2018-02-24 07:56 UTC, hnykda commented
Cool, thank for the answer. I think I could really nicely leverage this.

2018-02-26 10:42 UTC, dmanchon approved these changes

2018-02-26 10:48 UTC, dmanchon commented
@hnykda @elifiner nice to read you!.

Our usecase a large distributed queue with workers processing tasks in paralel, and pydump was one of the ideas that we are testing in order to post mortem debug the failed ones. The reason to fork is to add python3 support. So far with the changes that we made is working quite fine.

We will try again with the changes and merge after that. Of  course any help, request or issue report is more than welcomed :)

2018-02-26 11:15 UTC, masipcat requested changes
Thank you for your changes :-) I've just left a couple of comments.

2018-02-26 11:15 UTC, masipcat commented on pypm/__main__.py
> +    parser.add_argument('--debugger', default='ipdb', help='Debugger to use (must implement `post_morgem`)')
Could you change `ipdb` with `pdb`? The first one isn't installed by default.

2018-02-26 11:15 UTC, masipcat commented on example.py
> +import pandas as pd
I know we are using `requests` library on `crash_test.py`, but I would like to suggest to have a dependency-free `example.py`. We could add complex cases (with external dependencies) in a test script. What do you think?

2018-02-26 11:15 UTC, masipcat commented on example.py
> +    epsilon = t(2)
`t()` is not defined. Is this the desired behavior?

2018-02-27 18:06 UTC, masipcat commented
Hey @hnykda.

I'll modify the requested changes, resolve the conflicts and merge your changes. 

Thank you again for your contribution!

2018-02-27 18:16 UTC, merged

2018-02-27 19:15 UTC, hnykda commented
Hey! Sorry, I wasn't able to get back to it earlier... Thanks